"""add category table

Revision ID: 25c776fe1108
Revises: d81584014f68
Create Date: 2022-03-13 18:30:51.050334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c776fe1108'
down_revision = 'd81584014f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('moneyoperation', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moneyoperation', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moneyoperation', type_='foreignkey')
    op.drop_column('moneyoperation', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
